### ISSUE TITLE
Settings.json does not remove profile specific items

### ISSUE THREAD

**Issue by Munsio** [aaronpowell/vscode-profile-switcher#13] opened 2019-08-01 07:54 UTC
**Versions:**
App: VSCodium - 1.36.1
OS: Mac Mojave - 10.14.6
Profile Switcher: 0.3.2

I don't know if this is a bug or behaviour:

If i switch from my Base profile to my GO profile the go-extension settings are correctly copied to the settings.json
If i switch then from my GO profile to my PHP profile the extensions are correctly removed/added but all the go-extension related settings are present at the root level of the settings.json

Expected:
By switching from the GO to the PHP profile the go relevant settings should be removed.

**Comment by aaronpowell** [comment] 2019-08-01 10:58
This is expected behaviour. The extension isn't smart enough to know which settings belong to which profile, and because the uninstall isn't a "graceful" one (it just deletes the extension off disk) the sessions won't get removed.

When you switch profiles it is an additive approach to the `settings.json` file, so any settings you already have will be merged with the new settings.

**Closed by aaronpowell** 2019-08-01 10:58 UTC
